# <div class="girk"> NumPy Essential</div><i class="fa fa-lightbulb-o "></i>

# NumPy Array Types and Creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


## Array Types and conversions between types

In [3]:
integers = np.array([10,20,30,40,50])
print(integers)

[10 20 30 40 50]


In [4]:
integers[2]

30

In [5]:
integers[0] = 60
integers

array([60, 20, 30, 40, 50])

In [6]:
integers[0] = 21.5
integers

array([21, 20, 30, 40, 50])

In [7]:
integers.dtype

dtype('int32')

In [8]:
smallerIntegers = np.array(integers,dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [9]:
integers.nbytes

20

In [10]:
smallerIntegers.nbytes

5

In [11]:
Overflow = np.array([127,128,129],dtype=np.int8)
Overflow

array([ 127, -128, -127], dtype=int8)

In [12]:
floats = np.array([1.2,2.4,3.5,4.8,5.7,6.2,7.9])
print(floats)

[1.2 2.4 3.5 4.8 5.7 6.2 7.9]


In [13]:
floats.dtype

dtype('float64')

## Multidimensional Array

In [14]:
import numpy as np

In [15]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
nums[0,0]

1

In [17]:
nums[1,4]

10

In [18]:
nums[1,2]

8

In [19]:
nums.ndim

2

In [20]:
multi_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
multi_arr[1,0,2]

9

In [22]:
multi_arr[0,1,2]

6

## Creating arrays from Lists and other Python structures

In [23]:
import numpy as np

In [24]:
first_list = [1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
first_array = np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
second_list = [1,2,3,-1.23,50,128000.56,4.56]
second_list

[1, 2, 3, -1.23, 50, 128000.56, 4.56]

In [27]:
second_array = np.array(second_list)
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [28]:
second_array.dtype

dtype('float64')

In [29]:
third_list = ['Ann',11111,'Feter',11112,'Sussan',11113,'jhon',111114]
third_list

['Ann', 11111, 'Feter', 11112, 'Sussan', 11113, 'jhon', 111114]

In [30]:
third_array = np.array(third_list)
third_array

array(['Ann', '11111', 'Feter', '11112', 'Sussan', '11113', 'jhon',
       '111114'], dtype='<U11')

In [31]:
first_tuple = (5,10,12,18,20)
first_tuple

(5, 10, 12, 18, 20)

In [32]:
array_from_tuple = np.array(first_tuple)
array_from_tuple

array([ 5, 10, 12, 18, 20])

In [33]:
array_from_tuple.dtype

dtype('int32')

In [34]:
multi_dim_list = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
multi_dim_list

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [35]:
arr_from_multi_dim_list = np.array(multi_dim_list)
arr_from_multi_dim_list

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Intrisic NumPy array creation

In [36]:
import numpy as np

integers_array = np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
integers_second_array = np.arange(100,170)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169])

In [38]:
integers_third_array = np.arange(100,181,3)
integers_third_array

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136,
       139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175,
       178])

In [39]:
first_floats_arr = np.linspace(50,70)
first_floats_arr

array([50.        , 50.40816327, 50.81632653, 51.2244898 , 51.63265306,
       52.04081633, 52.44897959, 52.85714286, 53.26530612, 53.67346939,
       54.08163265, 54.48979592, 54.89795918, 55.30612245, 55.71428571,
       56.12244898, 56.53061224, 56.93877551, 57.34693878, 57.75510204,
       58.16326531, 58.57142857, 58.97959184, 59.3877551 , 59.79591837,
       60.20408163, 60.6122449 , 61.02040816, 61.42857143, 61.83673469,
       62.24489796, 62.65306122, 63.06122449, 63.46938776, 63.87755102,
       64.28571429, 64.69387755, 65.10204082, 65.51020408, 65.91836735,
       66.32653061, 66.73469388, 67.14285714, 67.55102041, 67.95918367,
       68.36734694, 68.7755102 , 69.18367347, 69.59183673, 70.        ])

In [40]:
second_floats_arr = np.linspace(20,30,5)
second_floats_arr

array([20. , 22.5, 25. , 27.5, 30. ])

In [41]:
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.26835943, 0.02163161, 0.5883056 , 0.3417386 , 0.32026013,
       0.05153709, 0.95295063, 0.06198589, 0.52701818, 0.06190514])

In [42]:
second_rand_arr = np.random.rand(3,3)
second_rand_arr

array([[0.76189788, 0.12628587, 0.85044847],
       [0.36256713, 0.08497414, 0.72402115],
       [0.02563154, 0.57310884, 0.14396885]])

In [43]:
thirst_rand_arr = np.random.randint(0,200,20)
thirst_rand_arr

array([ 40, 187,   1, 159, 109, 137, 105,  19, 194,  92, 159,  95,  62,
        28, 105,  59,   6,  40, 104,  48])

## Creating arrays filled with constant values

In [44]:
import numpy as np

first_z_array = np.zeros(4)
first_z_array

array([0., 0., 0., 0.])

In [45]:
second_z_array = np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
first_ones_array = np.ones(7)
first_ones_array

array([1., 1., 1., 1., 1., 1., 1.])

In [47]:
second_ones_array = np.ones((3,6))
second_ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
third_ones_array = np.ones((4,5),dtype = int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
first_fill_array = np.empty(10,dtype = int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [50]:
first_full_array = np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [51]:
second_full_array = np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

## Finding the shape and size of an array

In [52]:
import numpy as np

first_arr = np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
second_arr = np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [54]:
third_arr = np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [55]:
np.shape(first_arr)

(20,)

In [56]:
np.shape(second_arr)

(10, 2)

In [57]:
np.shape(third_arr)

(2, 2, 2)

In [58]:
np.size(first_arr)

20

In [59]:
np.size(second_arr)

20

In [60]:
np.size(third_arr)

8

# Manipulate NumPy Arrays

## Adding, removing, and sorting elements

In [61]:
import numpy as np

first_arr = np.array([1,2,3,5])
first_arr

array([1, 2, 3, 5])

In [62]:
new_first_arr = np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [63]:
second_arr = np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [64]:
new_second_arr = np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [65]:
third_arr = np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [66]:
del_arr = np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [67]:
integers_arr = np.random.randint(0,20,20)
integers_arr

array([ 3,  0, 11, 10,  2,  9, 11, 11,  8, 11, 11, 12, 19,  1,  2, 14,  6,
       13,  4,  6])

In [68]:
print(np.sort(integers_arr))

[ 0  1  2  2  3  4  6  6  8  9 10 11 11 11 11 11 12 13 14 19]


In [69]:
integers_2dim_arr = np.array([[3,2,5,7,6],[5,8,3,1,0]])
integers_2dim_arr

array([[3, 2, 5, 7, 6],
       [5, 8, 3, 1, 0]])

In [70]:
print(np.sort(integers_2dim_arr))

[[2 3 5 6 7]
 [0 1 3 5 8]]


In [71]:
colors = np.array(['orange','red','green','blue','white','pink','black'])
colors

array(['orange', 'red', 'green', 'blue', 'white', 'pink', 'black'],
      dtype='<U6')

In [72]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white']


## Copies and views

In [73]:
import numpy as np

students_ids_number = np.array([1111,1212,1313,1414,1515,1616,1717])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717])

In [74]:
students_ids_number_reg = students_ids_number
print('id of student ids number',id(students_ids_number))
print('id of students_ids_number_reg',id(students_ids_number_reg))

id of student ids number 2036135294416
id of students_ids_number_reg 2036135294416


In [75]:
students_ids_number_reg[1] = 2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717]
[1111 2222 1313 1414 1515 1616 1717]


In [76]:
students_ids_number_cp = students_ids_number.copy()
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717]


In [77]:
print(students_ids_number_cp == students_ids_number)

[ True  True  True  True  True  True  True]


In [78]:
print('id of student ids number',id(students_ids_number))
print('id of students_ids_number_cp',id(students_ids_number_cp))

id of student ids number 2036135294416
id of students_ids_number_cp 2036155293936


In [79]:
students_ids_number[0] = 1000
print('Original: ', students_ids_number)
print('Copy: ',students_ids_number_cp)

Original:  [1000 2222 1313 1414 1515 1616 1717]
Copy:  [1111 2222 1313 1414 1515 1616 1717]


In [80]:
students_ids_numberu_v = students_ids_number.view()

In [81]:
students_ids_numberu_v[0] = 2000
print('Original: ', students_ids_number)
print('View: ', students_ids_numberu_v)

Original:  [2000 2222 1313 1414 1515 1616 1717]
View:  [2000 2222 1313 1414 1515 1616 1717]


In [82]:
print(students_ids_number_cp.base)
print(students_ids_numberu_v.base)

None
[2000 2222 1313 1414 1515 1616 1717]


## Reshaping Array

In [83]:
import numpy as np

first_arr = np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
second_arr = np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
third_arr = np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [86]:
fourth_arr = np.reshape(first_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [87]:
fifth_arr = np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print('Dimensions of fifth_arr is', fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is 3


In [88]:
sixth_arr = np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
seventh_arr_flat = np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [90]:
eighth_arr_flat = sixth_arr.flatten()
print('eighth_arr_flat: ',eighth_arr_flat)
ninth_arr_rav = sixth_arr.ravel()
print('ninth_arr_rav: ',ninth_arr_rav)

eighth_arr_flat:  [1 2 3 4 5 6]
ninth_arr_rav:  [1 2 3 4 5 6]


In [91]:
eighth_arr_flat[0] = 100
ninth_arr_rav[0] = 200

In [92]:
print('eighth_arr_flat: ',eighth_arr_flat)
print('ninth_arr_rav: ',ninth_arr_rav)
print('sixth_arr: ', sixth_arr)

eighth_arr_flat:  [100   2   3   4   5   6]
ninth_arr_rav:  [200   2   3   4   5   6]
sixth_arr:  [[200   2]
 [  3   4]
 [  5   6]]


## Indexing and Slicing

In [93]:
import numpy as np

twodim_arr = np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
twodim_arr[1,1]

5

In [95]:
twodim_arr[1]

array([4, 5, 6, 7])

In [96]:
threedim_arr = np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [97]:
threedim_arr[0,2,3]

13

In [98]:
threedim_arr[2,-1,-1]

59

In [99]:
onedim_arr = np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [101]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [102]:
onedim_arr[-3:]

array([7, 8, 9])

In [103]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [104]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [106]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [107]:
twodim_arr[:,2]

array([ 2,  6, 10])

## Joining and splitting arrays

In [108]:
import numpy as np

first_arr = np.arange(1,11)
second_arr = np.arange(11,21)
print('first_arr',first_arr)
print('second_arr',second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [109]:
con_arr = np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [110]:
third_2darr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [111]:
fourth_2darr = np.array([[11,12,13,14,15],[16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [112]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr))
con2d_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [113]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [114]:
st_arr = np.stack((first_arr,second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [115]:
hst_arr = np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [116]:
vst_arr = np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [117]:
fifth_arr = np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
sp_arr = np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [119]:
print(sp_arr[2])

[7 8 9]


In [120]:
sp_arr = np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [121]:
hs_arr = np.hsplit(third_2darr,5)
hs_arr

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [122]:
vs_arr = np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

# Functions and Operations

## Arithmetic operations and functions

In [123]:
import numpy as np

a = np.arange(1,11)
b = np.arange(21,31)
print('a',a)
print('b',b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [124]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [125]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [126]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [127]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [128]:
a**b

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824],
      dtype=int32)

In [129]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [131]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [132]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [133]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [134]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0], dtype=int32)

In [135]:
np.power(a,b)

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824],
      dtype=int32)

In [136]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## Broadcasting

In [137]:
import numpy as np

a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [139]:
a + b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [140]:
c = np.arange(1,3)
c

array([1, 2])

In [141]:
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [142]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [143]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [144]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

## Aggregate funtions

In [145]:
import numpy as np

first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [146]:
second_arr = np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [147]:
third_arr = np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [148]:
first_arr.sum()

550

In [149]:
second_arr.sum()

450

In [150]:
third_arr.sum()

550

In [151]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [152]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [153]:
first_arr.prod()

1704722432

In [154]:
second_arr.prod()

-1786839040

In [155]:
third_arr.prod()

1704722432

In [156]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [157]:
np.average(first_arr)

55.0

In [158]:
np.average(second_arr)

50.0

In [159]:
np.average(third_arr)

55.0

In [160]:
np.min(first_arr)

10

In [161]:
np.max(first_arr)

100

In [162]:
np.mean(first_arr)

55.0

In [163]:
np.std(first_arr)

28.722813232690143

In [164]:
np.var(second_arr)

666.6666666666666

In [165]:
np.var(third_arr)

825.0

## How to get unique items and counts

In [166]:
import numpy as np

first_arr = np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [167]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [168]:
second_arr = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [169]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [170]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [171]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [172]:
np.unique(first_arr,return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11], dtype=int64))

In [173]:
np.unique(first_arr,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([3, 3, 1, 1, 1, 1, 2, 1, 1], dtype=int64))

## Transpose like operations

In [174]:
import numpy as np

first_2dimarr = np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [175]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [176]:
second_2dimarr = np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [177]:
np.transpose(second_2dimarr)

array([[0, 2, 4],
       [1, 3, 5]])

In [179]:
first_3dimarr = np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [180]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [181]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Reversing an array

In [182]:
import numpy as np

arr_1dim = [10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [183]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [184]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [185]:
arr_2dim = np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [186]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [187]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [188]:
arr_3dim = np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [189]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [190]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])